name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -r docs/requirements.txt
      - name: Sphinx build
        working-directory: ./docs
        run: |
          sphinx-build . _build
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #   with:
      #     publish_branch: gh-pages
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: docs/_build
      #     force_orphan: true
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # location of the coverage artifacts
          path: "./docs/_build"
  deploy:
    runs-on: ubuntu-latest
    needs: docs
    permissions:
      pages: write
      id-token: write
    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
